using Shared;
using Workers;

namespace WorkersDotNet
{
    /// <summary>
    /// Sample: the Workers Cache API (<c>caches.default</c>).
    /// </summary>
    /// <remarks>
    /// The first GET for a cache key produces a fresh payload and stores the
    /// response in the cache. Every later GET for the same key is answered from
    /// the cache, so <c>EntryId</c> and <c>GeneratedAtUtc</c> stay frozen while
    /// the <c>x-cache</c> response header flips from "miss" to "hit".
    /// A POST deletes the entry again, which makes the next GET a miss.
    /// The full request URL (including <c>?key=</c> used by the UI) is the cache
    /// key, so different keys are cached independently.
    /// </remarks>
    public static class CacheEndpoint
    {
        public static async Task<Response> HandleAsync(Request request, Context context)
        {
            var cacheKey = request.Url.ToString();

            if (request.Method == "POST")
                return await PurgeAsync(cacheKey);

            var cached = await CacheStorage.Default.MatchAsync(cacheKey);
            if (cached is not null)
            {
                return cached
                    .WithHeader("x-cache", "hit")
                    .WithHeader("x-cache-key", cacheKey)
                    .WithHeader("x-cache-note", "Served from caches.default on the edge")
                    .WithHeader("cache-control", "no-store");
            }

            var payload = new CachePayload(
                cacheKey,
                Guid.NewGuid().ToString(),
                DateTimeOffset.UtcNow.ToString("O"),
                "Generated by the worker, then stored in the Cache API.");

            // The stored copy needs a cacheable "cache-control": the Cache API
            // quietly refuses to store a response marked "no-store". It is built
            // from its own response instance, because a Response body can only be
            // handed to the Response constructor once.
            var stored = Response.Json(payload, 200)
                .WithHeader("x-cache", "miss")
                .WithHeader("x-cache-key", cacheKey)
                .WithHeader("cache-control", "max-age=300");

            // Writing to the cache must finish even though the response is
            // returned right away, so hand the task to the runtime.
            context.WaitUntil(CacheStorage.Default.PutAsync(cacheKey, stored));

            // The client response uses "no-store" so the browser never serves its
            // own copy; every click then really reaches the worker and the
            // hit/miss flips stay visible.
            return Response.Json(payload, 200)
                .WithHeader("x-cache", "miss")
                .WithHeader("x-cache-key", cacheKey)
                .WithHeader("x-cache-note", "Freshly generated and written to caches.default")
                .WithHeader("cache-control", "no-store");
        }

        static async Task<Response> PurgeAsync(string cacheKey)
        {
            var deleted = await CacheStorage.Default.DeleteAsync(cacheKey);

            var message = deleted
                ? "Cache entry deleted. The next GET is a cache miss."
                : "There was no cache entry for this key, so the next GET is already a miss.";

            return Response.Json(new CachePurgeResult(deleted, cacheKey, message), 200)
                .WithHeader("x-cache", "purged")
                .WithHeader("x-cache-key", cacheKey)
                .WithHeader("cache-control", "no-store");
        }
    }
}
